categories:
  - Advertising
  - Meals & Entertainment
  - Insurance
  - Business tax, fees, licences
  - Office expenses
  - Supplies
  - Legal, accounting, and other professional fees
  - Management and administration fees
  - Rent
  - Maintenance and repairs
  - Salaries, wages, and benefits
  - Telephone and utilties
  - Travel
  - Delivery, freight, and express
  - Motor vehcie expenses
  - Health Medical
  - Other expenses
